FROM node:22-alpine AS build
WORKDIR /app
RUN corepack enable
ARG VITE_API_URL=/api
ENV VITE_API_URL=$VITE_API_URL
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/web/package.json apps/web/package.json
COPY packages/eslint-config/package.json packages/eslint-config/package.json
RUN pnpm install --frozen-lockfile --filter my-commit-client...
COPY packages ./packages
COPY apps/web ./apps/web
RUN pnpm --filter my-commit-client build

FROM caddy:2-alpine
COPY --from=build /app/apps/web/dist /usr/share/caddy
COPY Caddyfile /etc/caddy/Caddyfile
