export const FLOW_EXAPLE_DATA = [
  {
    name: '08:00',
    giveup: 0,
    boring: 0,
    tryAgain: -0,
    totalSurrender: 0,
    totalTryAgain: -0,
  },
  {
    name: '10:00',
    giveup: 2,
    boring: 2,
    tryAgain: -4,
    totalSurrender: 4,
    totalTryAgain: -4,
  },
  {
    name: '12:00',
    giveup: 3,
    boring: 0,
    tryAgain: -0,
    totalSurrender: 7,
    totalTryAgain: -4,
  },
  {
    name: '14:00',
    giveup: 3,
    boring: 0,
    tryAgain: -0,
    totalSurrender: 10,
    totalTryAgain: -4,
  },
  {
    name: '16:00',
    giveup: 0,
    boring: 4,
    tryAgain: -2,
    totalSurrender: 14,
    totalTryAgain: -6,
  },
  {
    name: '18:00',
    giveup: 0,
    boring: 4,
    tryAgain: -0,
    totalSurrender: 18,
    totalTryAgain: -6,
  },
  {
    name: '20:00',
    giveup: 2,
    boring: 0,
    tryAgain: -2,
    totalSurrender: 20,
    totalTryAgain: -8,
  },
  {
    name: '22:00',
    giveup: 2,
    boring: 0,
    tryAgain: -1,
    totalSurrender: 22,
    totalTryAgain: -9,
  },
  {
    name: '24:00',
    giveup: 2,
    boring: 0,
    tryAgain: -2,
    totalSurrender: 24,
    totalTryAgain: -11,
  },
  {
    name: '26:00',
    giveup: 0,
    boring: 0,
    tryAgain: -0,
    totalSurrender: 24,
    totalTryAgain: -11,
  },
];

export const FLOW_EXAPLE_RATIO = {
  totalSurrenderRatio: 67,
  actualSurrenderRatio: 50,
  totalTryAgainRatio: 60,
};
